//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoMDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sexo { get; set; }
        public System.DateTime DatadeNasc { get; set; }
        public string NIF { get; set; }
        public string Morada { get; set; }
        public string TipoConta { get; set; }
    }
}
